# Generated by Django 4.0.4 on 2022-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_claim', models.IntegerField()),
                ('select_claim', models.IntegerField()),
                ('name_claim', models.CharField(max_length=1024)),
                ('parent_claim', models.CharField(max_length=1024)),
                ('class_claim', models.IntegerField()),
                ('concert_claim', models.CharField(max_length=1024)),
                ('sity_claim', models.CharField(max_length=1024)),
                ('prog_claim', models.TextField()),
                ('url_claim', models.URLField()),
            ],
        ),
    ]
